---
##
# Grin Volumes


apiVersion: v1
kind: PersistentVolume
metadata:
  name: grinblockchain-grin-0
  labels:
    node: lucy
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/grin-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - lucy
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grinblockchain-grin-0
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      node: lucy


#---
#
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: grinblockchain-grin-1
#  labels:
#    node: lucy
#spec:
#  capacity:
#    storage: 50Gi
#  accessModes:
#  - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Retain
#  storageClassName: local-storage
#  local:
#    path: /data/grin-1
#  nodeAffinity:
#    required:
#      nodeSelectorTerms:
#      - matchExpressions:
#        - key: kubernetes.io/hostname
#          operator: In
#          values:
#          - lucy
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: grinblockchain-grin-1
#spec:
#  storageClassName: local-storage
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 50Gi
#  selector:
#    matchLabels:
#      node: lucy
#
#
#---
#
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: grinblockchain-grin-2
#  labels:
#    node: lucy
#spec:
#  capacity:
#    storage: 50Gi
#  accessModes:
#  - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Retain
#  storageClassName: local-storage
#  local:
#    path: /data/grin-2
#  nodeAffinity:
#    required:
#      nodeSelectorTerms:
#      - matchExpressions:
#        - key: kubernetes.io/hostname
#          operator: In
#          values:
#          - lucy
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: grinblockchain-grin-2
#spec:
#  storageClassName: local-storage
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 50Gi
#  selector:
#    matchLabels:
#      node: lucy
