---
# P2p port is public
apiVersion: v1
kind: Service
metadata:
  name: grin-p2p
  labels:
    app: grin
spec:
  type: LoadBalancer
  ports:
  - name: ptop
    port: 13414
    protocol: TCP
  selector:
    app: grin
---
apiVersion: v1
kind: Service
metadata:
  name: grin
  labels:
    app: grin
spec:
  ports:
  - port: 13413
    protocol: TCP
    name: grinapi
  - port: 13416
    protocol: TCP
    name: grinstratum
  selector:
    app: grin
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: grin
spec:
  selector:
    matchLabels:
      app: grin
  serviceName: grin
  replicas: 1
  template:
    metadata:
      labels:
        app: grin
    spec:
      containers:
      - name: grin
#        image: grinpool/grin:test
        image: docker.mwgrinpool.com:5001/grin:latest
        #        command: ["sleep", "9999999"]
        command: ["/run.sh"]
        ports:
        - containerPort: 13413
        - containerPort: 13414
        - containerPort: 13416
        volumeMounts:
        - name: grinblockchain
          mountPath: /server
      - name: sharewatcher
#        image: grinpool/logstash:test
        image: docker.mwgrinpool.com:5001/logstash:latest
        command: ["/run.sh", "grinsharefilter.conf"]
#        command: ["sleep", "9999999"]
        env:
        - name: RMQ_USER
          valueFrom:
            secretKeyRef:
              name: rmq
              key: username.txt
        - name: RMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rmq
              key: password.txt
        volumeMounts: # directory inside container
        - name: grinblockchain
          mountPath: /server
      imagePullSecrets:
      - name: regsecret
  volumeClaimTemplates:
  - metadata:
      name: grinblockchain
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
