apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: poolstats
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: poolstats
    spec:
      containers:
      - name: grin-pool
        image: docker.mwgrinpool.com:5001/services:latest
        args: ["/usr/local/bin/poolStats.py"]
        env:
        - name: DEBUG_HOLD
          value: 
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
#        volumeMounts: # directory inside container
#        - mountPath: /services
#          name: xxx
#      volumes: # directory location on host
#      - name: xxx
#        hostPath:
#          path: /data/services
      imagePullSecrets:
      - name: regsecret

