kind: ConfigMap
apiVersion: v1
metadata:
  name: splunk-forwarder-config
data:
  outputs.conf: |
     # Send logs to splunk
     [tcpout:group1]
     server=splunk:9997
  inputs.conf: |
     # watch all files in <path>
     [monitor:///var/log/containers/*.log]
     # extract `host` from the first group in the filename
     host_regex = /var/log/containers/(.*)_.*_.*\.log
     # set source type to Kubernetes
     sourcetype = kubernetes
--- 
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: splunk-forwarder-daemonset
spec:
  template:
    metadata:
      labels:
         app: splunk-forwarder
    spec:
      containers:
      - name: splunkuf
        image: docker.io/grinpool/universalforwarder:latest
        env:
        - name: SPLUNK_START_ARGS
          value: "--accept-license"
        - name: SPLUNK_USER
          value: "root"
        - name: SPLUNK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: splunk
              key: password.txt
        volumeMounts:
        - mountPath: /var/run/docker.sock
          readOnly: true
          name: docker-socket
        - mountPath: /var/log/containers
          readOnly: true
          name: container-logs
        - mountPath: /var/lib/docker/containers
          readOnly: true
          name: docker-container-logs
        - mountPath: /configmap/
          name: splunk-config
        - mountPath: /var/log/pods
          readOnly: true
          name: pod-logs
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: docker-container-logs
          hostPath:
            path: /var/lib/docker/containers
        - name: container-logs
          hostPath:
            path: /var/log/containers
        - name: pod-logs
          hostPath:
            path: /var/log/pods
        - name: splunk-config
          configMap:
            name: splunk-forwarder-config
