apiVersion: v1
kind: Service
metadata:
  name: webui
  labels:
    run: webui
spec:
  ports:
  - port: 13424
    targetPort: 3005
    protocol: TCP
    name: webui
  selector:
    run: webui
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: webui
    spec:
      containers:
      - name: webui
        image: docker.mwgrinpool.com:5001/webui-js:latest
#        command: ["sleep", "9999999"]
        command: ["yarn", "start"]
        ports:
        - containerPort: 13524
        env:
        - name: NODE_ENV
          value: production
      imagePullSecrets:
      - name: regsecret

